### ISSUE TITLE
NBA dataset splits

### ISSUE THREAD

**Issue by nicolasugrinovic** [luyangzhu/NBA2K-dataset#4]
Hi, 
Kudos for the great work and the code release. 

I wanted to know how do you exactly make the train, test, and validation splits. In the paper, you mention the number of examples for each split, but do not mention any more details, e.g., which characters are used for test? 

I would very much appreciate your answer. 

Thanks in advance!

**Comment by luyangzhu** [comment]
Hi, 

The dataset split is provided here: https://github.com/luyangzhu/NBA-Players/blob/d0ac029c18ff42dcab3515a603733fe564116820/img_to_mesh/src/constants.py#L155

I split the data by players, making sure test/valid players are never seen during training. Hope it helps.

**Comment by nicolasugrinovic** [comment]
Thanks for the prompt answer, very much appreciated!
