### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by nicolasugrinovic** [luyangzhu/NBA2K-dataset#5]
Hi, 

Is there any way to access the **intrinsic camera parameters**? I see that you have a `proj_mat` for each player. Is it possible to get the intrinsics from that matrix? As I understand it is straightforward to do this if `proj_mat` was homogeneous, however, it seems this is not the case.

This is an example of a `proj_mat` for a certain image:
![Selection_999(1191)](https://user-images.githubusercontent.com/25443240/152826986-3a295591-66ac-43dd-9aa9-06ff384c1ccc.png)

Thanks!

**Comment by luyangzhu** [comment]
We can only extract `proj_mat` from the game engine. I've tried to compute camera intrinsics from the `proj_mat`, but failed. It seems the game engine baked several matrices into this one. If you managed to do it, feel free to open a pull request.

**Comment by nicolasugrinovic** [comment]
Ok, thanks for the response. Yes, it seems that the engine then mixes a view matrix with a projection matrix somehow fusing A, R, and T and the type of projection used. So you go from world space directly to clip space. Maybe one could use SVD for this, but I guess it is not that straightforward.
